spring:
  #静态资源处理
#  resources:
#    #启动默认静态资源处理
#    add-mappings: true
#    cache:
#      cachecontrol:
#        #缓存响应时间 单位秒
#        max-age: 3600
#      chain:
#        #资源链启动缓存 默认启动
#        cache: true
#        #启用资源链 默认禁用
#        enable: true
#        #启用压缩资源（gzip,brotli）解析 默认禁用
#        compressed: true
#        #启用h5应用缓存 默认禁用
#        html-application-cache: true
#        #静态资源位置
#        static-location: classpath:/static/
  rabbitmq:
    #主机ip
    host: 192.168.32.129
    username: guest
    password: guest
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者只处理一条消息 处理完再处理下一条消息
        prefetch: 1
        #启动时是否默认启动容器 默认true
        auto-startup: true
        #被拒绝时 重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试 默认为false
        enabled: true
        #重试时间 默认为1000ms
        initial-interval: 1000ms
        #最大重试次数 默认3次
        max-attempts: 3
        #重试最大时间间隔 默认10000ms
        max-interval: 10000ms
        #重试间隔乘数:比如2.0 第一次等10s 第二次等20s 第三次就等40s
        multiplier: 1






  #thymeleaf配置  模板引擎
  thymeleaf:
    #不需要缓存
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      #连接池
      pool-name: DateHikariCP
      #空闲时最小连接数
      minimum-idle: 5
      #空闲连接超时时间 默认600000（10分中国）
      idle-timeout: 600000
      #连接池中允许的最大连接数 默认10
      maximum-pool-size: 10
      #开启自动提交
      auto-commit: true
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟
      max-lifetime: 1800000
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      #数据库连接测试语句
      connection-test-query: SELECT 1

#redis配置
  redis:
    #服务器地址
    host: 192.168.32.128
    port: 6379
    #默认数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 8
        #最大连接阻塞等待时间 默认-1 （永久）
        max-wait: 10000ms
        #最大空闲连接 默认 8
        max-idle: 200
        #最小空闲连接 默认0
        min-idle: 5



#Mybatis-plus配置
mybatis-plus:
  #??Mapper.xml文件的位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??Mybatis??????????????????
  type-aliases-package: com.yunlong.seckilldemo.pojo


#MyBatis SQL??????????????mapper?????
logging:
  level:
    com.yunlong.seckilldemo.mapper: debug


